(executable
  (name Client)
  (libraries
    ctypes
    ctypes.stubs
    ctypes.foreign
  )
  (link_flags "-linkall")
  (ctypes
    (external_library_name Ctypes0)
    (build_flags_resolver (vendored (c_flags :standard) (c_library_flags :standard)))
    (type_description
      (instance Types)
      (functor Type_description)
    )
    (function_description
      (instance Functions)
      (functor Function_description)
    )
    (generated_entry_point CFuns)
  )
  (flags (:standard -w -32-33))
)
